services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env_for_db
    ports:
      - '5432:5432'
    networks:
      - my_network
  
  test_task:
    build: 
      context: .
    env_file:
      - .env-docker-comm
    container_name: app
    expose:
      - "8000"
    depends_on:
      - redis
      - test_db  
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    networks:
      - my_network
      

networks:
  my_network:
    driver: bridge