services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env_for_db
    ports:
      - '5432:5432'
    networks:
      - my_network
  
  test_task:
    build: 
      context: .
    env_file:
      - .env
    container_name: app
    expose:
      - "8000"
    ports:
      - '8000:8000'
    depends_on:
      - db  

    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    networks:
      - my_network
      

networks:
  my_network:
    driver: bridge